spring.application.name=qr-generator
server.port=8081
# H2 DB
spring.datasource.url=jdbc:h2:./data/qrdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Cargar las clases al iniciar
spring.jpa.hibernate.ddl-auto=update

